//
//  DoodlePadStore.swift
//  Doodle in SwiftUI
//
//  Created by 倪僑德 on 2021/12/25.
//  Copyright (c) 2021 iOS@Taipei in iPlayground 2020. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,

import Foundation
import SwiftUI

protocol DoodlePadPresentationLogic {
    func updateDoodles(_ doodles: [DrawDoodle])
}

protocol DoodlePadStoreSpec: AnyObservableObject {
    var doodles: [DrawDoodle] { get set }
    func add(_ doodle: DrawDoodle)
}

final class DoodlePadStore: ObservableObject, DoodlePadPresentationLogic, DoodlePadStoreSpec {
    
    // MARK: DoodlePadStoreSpec
    
    @Published var doodles: [DrawDoodle] = []
    
    func add(_ doodle: DrawDoodle) {
        doodles.append(doodle)
    }
    // MARK: Private properties
    
    // MARK: DoodlePadPresentationLogic
    
    func updateDoodles(_ doodles: [DrawDoodle]) {
        self.doodles = doodles
    }
}
