//
//  DoodlePadInteractor.swift
//  Doodle in SwiftUI
//
//  Created by 倪僑德 on 2021/12/25.
//  Copyright (c) 2021 iOS@Taipei in iPlayground 2020. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,

import Combine

protocol DoodlePadBusinessLogic {
    func handleDoodlesUpdate(_ doodles: [DrawDoodle])
}

final class DoodlePadInteractor: DoodlePadBusinessLogic {
    
    var stateStore: DoodlePadPresentationLogic?
    
    func handleDoodlesUpdate(_ doodles: [DrawDoodle]) {
        guard doodles.isEmpty == false else { return }
        var topIndex: Int = 0
        for i in 0 ..< doodles.count {
            if doodles[i].zPriority > doodles[0].zPriority {
                doodles[topIndex].isFocus = false
                topIndex = i
                doodles[i].isFocus = true
            } else {
                doodles[i].isFocus = false
            }
        }
    }
}
