//
//  DoodleModels.swift
//  Doodles in SwiftUI
//
//  Created by 倪僑德 on 2021/12/27.
//  Copyright (c) 2021 iOS@Taipei in iPlayground 2020. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,

import Foundation

enum Doodle {
    
    /*
    enum UseCase {
        struct Request {
            
        }
        
        struct Response {
            
        }
    }
    */
}
